const products = [
  {
    _id: "001",
    name: "Men Checked Shirt",
    img: "https://rukminim1.flixcart.com/image/880/1056/kwtkxow0/shirt/c/u/n/xl-brd-white-p-v-creations-original-imag9f3yxz7d89t4.jpeg?q=50",
    alt: "mens shirt",
    brand: "Roadster",
    newPrice: 1750,
    oldPrice: 2499,
    discount: 67,
    size: "L",
    idealFor: "M",
    rating: 4.2,
  },
  {
    _id: "002",
    name: "Women Crop Top",
    img: "https://rukminim1.flixcart.com/image/880/1056/krf91u80/top/g/n/v/xs-lbt-13-maroon-london-belly-original-imag57qgzcm3hsmv.jpeg?q=50",
    alt: "womens top",
    brand: "Forever 21",
    newPrice: 750,
    oldPrice: 1499,
    discount: 75,
    size: "M",
    idealFor: "W",
    rating: 4.5,
  },
  {
    _id: "003",
    name: "Women Solid Shirt",
    img: "https://rukminim1.flixcart.com/image/880/1056/kf2v3ww0/top/z/f/t/l-044-yukon01-original-imafvhkejzfhqaqz.jpeg?q=50",
    alt: "Women shirt",
    brand: "Zara",
    newPrice: 2750,
    oldPrice: 3499,
    discount: 46,
    size: "L",
    idealFor: "W",
    rating: 3.9,
  },
  {
    _id: "004",
    name: "Men Solid Shirt",
    brand: "Peter England",
    img: "https://rukminim1.flixcart.com/image/580/696/kwzap3k0/shirt/r/q/j/l-lstr-acqua-p-v-creations-original-imag9jggj6naa4cu.jpeg?q=50",
    alt: "mens shirt",
    newPrice: 2554,
    oldPrice: 3499,
    discount: 27,
    size: "XL",
    idealFor: "M",
    rating: 3.5,
  },
  {
    _id: "005",
    name: "Men Solid T-Shirt",
    brand: "Roadster",
    img: "https://rukminim1.flixcart.com/image/580/696/kz8qsnk0/t-shirt/g/z/n/m-db1024-42-3bros-original-imagbawh38j3ghzr.jpeg?q=50",
    alt: "mens t-shirt",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 21,
    size: "M",
    idealFor: "M",
    rating: 3.2,
  },
  {
    _id: "006",
    name: "Women Printed Top",
    img: "https://rukminim1.flixcart.com/image/580/696/kzhbfrk0/top/v/b/6/m-fancy-top-shree-villa-original-imagbhgpqkj9snta.jpeg?q=50",
    alt: "Women Printed Top",
    brand: "Zara",
    newPrice: 1750,
    oldPrice: 2499,
    discount: 27,
    size: "S",
    idealFor: "W",
    rating: 3.2,
  },
  {
    _id: "007",
    name: "Men Regular V Neck T-Shirt",
    img: "https://rukminim1.flixcart.com/image/580/696/k6gsk280/t-shirt/e/z/h/xl-pp-374-385-379-revesto-original-imafkxwnetcxt4xr.jpeg?q=50",
    alt: "mens t-shirt",
    brand: "DNMX",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 90,
    size: "XXL",
    idealFor: "M",
    rating: 2.2,
  },
  {
    _id: "008",
    name: "Women Regular Top",
    img: "https://rukminim1.flixcart.com/image/580/696/knni7ww0/top/o/m/o/s-dmp303-dmp-fashion-original-imag2a5qkjgjf22k.jpeg?q=50",
    alt: "Women Regular Top",
    brand: "Forever 21",
    newPrice: 2750,
    oldPrice: 3499,
    discount: 44,
    size: "XXL",
    idealFor: "W",
    rating: 2.2,
  },
   {
    _id: "009",
    name: "Women Solid T-Shirt",
    img: "https://rukminim1.flixcart.com/image/580/696/jzn0tjk0/t-shirt/t/y/g/s-fw-014-mrrd-s-first-wave-original-imaf2nxuqatamwhm.jpeg?q=50",
    alt: "Women t-shirt",
    brand: "Forever 21",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 39,
    size: "S",
    idealFor: "W",
    rating: 2.2,
  },
  {
    _id: "010",
    name: "Men Solid Casual Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/c/6/4/m-000001-dhaduk-original-imahaumphe4myxjf.jpeg?q=70",
    alt: "mens solid casual shirt",
    brand: "Dhaduk",
    newPrice: 899,
    oldPrice: 1499,
    discount: 40,
    size: "M",
    idealFor: "M",
    rating: 4.3
  },
  {
    _id: "011",
    name: "Men Striped Casual Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/0/s/1/3xl-sss23-csmssrt5611plus-instafab-plus-original-imagrbmfgvzphf8g.jpeg?q=70",
    alt: "mens striped casual shirt",
    brand: "Instafab Plus",
    newPrice: 999,
    oldPrice: 1899,
    discount: 47,
    size: "3XL",
    idealFor: "M",
    rating: 4.1
  },
  {
    _id: "012",
    name: "Men Slim Fit Casual Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/f/v/s/s-met-shirt1801-metronaut-original-imah8pshraqgemqr.jpeg?q=70",
    alt: "men slim fit casual shirt",
    brand: "Metronaut",
    newPrice: 849,
    oldPrice: 1699,
    discount: 50,
    size: "S",
    idealFor: "M",
    rating: 4.0
  },
  {
    _id: "013",
    name: "Women Printed Kurta Set",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/ethnic-set/z/v/o/s-pink-printed-kurta-pant-and-dupatta-set-for-women-shri-shyam-original-imaha6ycw635pxsr.jpeg?q=70",
    alt: "women printed kurta pant dupatta set",
    brand: "Shri Shyam",
    newPrice: 1199,
    oldPrice: 2399,
    discount: 50,
    size: "S",
    idealFor: "W",
    rating: 4.4
  },
  {
    _id: "014",
    name: "Men Printed T-Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-t-shirt/k/e/c/l-tblhnful-spy-d144-tripr-original-imahcjtu6ghwgpk7.jpeg?q=70",
    alt: "men printed t-shirt",
    brand: "TRIPR",
    newPrice: 499,
    oldPrice: 999,
    discount: 50,
    size: "L",
    idealFor: "M",
    rating: 4.0
  },
  {
    _id: "015",
    name: "Women Chanderi Ethnic Set",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/ethnic-set/o/z/n/3xl-chanderi-dishwa-fashion-original-imah8wgzrzsm49xh.jpeg?q=70",
    alt: "women chanderi ethnic set",
    brand: "Dishwa Fashion",
    newPrice: 1349,
    oldPrice: 2699,
    discount: 50,
    size: "3XL",
    idealFor: "W",
    rating: 4.1
  },
  {
    _id: "016",
    name: "Women Printed Saree",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/g/q/e/free-anisha-k-5-fashion-unstitched-original-imah4gxrfqa9p6qz.jpeg?q=70",
    alt: "women printed saree",
    brand: "Anisha K-5 Fashion",
    newPrice: 649,
    oldPrice: 1499,
    discount: 57,
    size: "Free",
    idealFor: "W",
    rating: 4.2
  },
  {
    _id: "017",
    name: "Boys Colorblock Hooded T-Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/e/v/h/11-12-years-cb-2-906-style-hood-blk-grey-m-uzee-original-imaguxrrxthps5vd.jpeg?q=70",
    alt: "kids hooded t-shirt",
    brand: "Uzee",
    newPrice: 399,
    oldPrice: 799,
    discount: 50,
    size: "11-12 Years",
    idealFor: "M",
    rating: 4.0
  },
  {
    _id: "018",
    name: "Men Slim Fit Striped Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/8/p/j/l-4mss4094-01-snitch-original-imahcz3shpveemkv.jpeg?q=70",
    alt: "men striped shirt",
    brand: "Snitch",
    newPrice: 1099,
    oldPrice: 2199,
    discount: 50,
    size: "L",
    idealFor: "M",
    rating: 4.3
  },
  {
    _id: "019",
    name: "Women Banarasi Saree",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/z/z/z/free-msf-banarasi-darkgreen-bfa-doroly-unstitched-original-imahdmksyhradcyg.jpeg?q=70",
    alt: "women banarasi saree",
    brand: "Doroly",
    newPrice: 799,
    oldPrice: 1999,
    discount: 60,
    size: "Free",
    idealFor: "W",
    rating: 4.4
  },
  {
    _id: "020",
    name: "Women Printed Saree",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/w/r/i/free-1873ps3-tasrika-unstitched-original-imah7m3bhm7brztc.jpeg?q=70",
    alt: "women printed saree",
    brand: "Tasrika",
    newPrice: 549,
    oldPrice: 1799,
    discount: 69,
    size: "Free",
    idealFor: "W",
    rating: 4.2
  },
  {
    _id: "021",
    name: "Men Formal Shirt – HouseOfCommon",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/7/w/x/l-c511-houseofcommon-original-imaheedr8cjdghvt.jpeg?q=70",
    alt: "men formal shirt houseofcommon",
    brand: "HouseOfCommon",
    newPrice: 1199,
    oldPrice: 2999,
    discount: 60,
    size: "L",
    idealFor: "M",
    rating: 4.2
  },
  {
    _id: "022",
    name: "Men Formal Shirt – Shimak PST-100",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/j/2/d/m-pst-100-shimak-original-imah9gsyhckaqztz.jpeg?q=70",
    alt: "men formal shirt shimak pst-100",
    brand: "Shimak",
    newPrice: 999,
    oldPrice: 2499,
    discount: 60,
    size: "M",
    idealFor: "M",
    rating: 4.0
  },
  {
    _id: "023",
    name: "Men Formal Shirt – Deemoon Satin14",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/i/2/r/s-satin14-deemoon-original-imahckprq6td5kgm.jpeg?q=70",
    alt: "men formal shirt deemoon satin14",
    brand: "Deemoon",
    newPrice: 1099,
    oldPrice: 2599,
    discount: 57,
    size: "XL",
    idealFor: "M",
    rating: 4.1
  },
  {
    _id: "024",
    name: "Men Formal Shirt – Vebnor FRML-ST2",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/t/u/d/xxl-frml-st2-vebnor-original-imahdtfqcx8hhrtb.jpeg?q=70",
    alt: "men formal shirt vebnor frml-st2",
    brand: "Vebnor",
    newPrice: 899,
    oldPrice: 2199,
    discount: 59,
    size: "XXL",
    idealFor: "M",
    rating: 3.9
  },
  {
    _id: "025",
    name: "Women Printed Saree – Samah Unstitched",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/u/o/m/free-4063s6384u-samah-unstitched-original-imahgvhghgtvgugr.jpeg?q=70",
    alt: "women printed saree samah unstitched",
    brand: "Samah",
    newPrice: 599,
    oldPrice: 1799,
    discount: 67,
    size: "Free",
    idealFor: "W",
    rating: 4.3
  },
  {
    _id: "026",
    name: "Women Saree – Designer Bollywood Fashion Style Litchi",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/b/s/n/free-749-pink-art-silk-designer-bollywood-fashion-style-litchi-original-imah7gc4hejdr2eq.jpeg?q=70",
    alt: "women art silk designer saree litchi",
    brand: "Bollywood Fashion Style",
    newPrice: 899,
    oldPrice: 2499,
    discount: 64,
    size: "Free",
    idealFor: "W",
    rating: 4.1
  },
  {
    _id: "027",
    name: "Women Saree – Salco Unstitched",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/k/3/j/free-1401-salco-unstitched-original-imah2y4fqzenn2ae.jpeg?q=70",
    alt: "women saree salco unstitched",
    brand: "Salco",
    newPrice: 649,
    oldPrice: 1599,
    discount: 59,
    size: "Free",
    idealFor: "W",
    rating: 4.0
  },
  {
    _id: "028",
    name: "Women Saree – Anand Unstitched",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/1/v/a/free-gk2-lb-1747-4-anand-sarees-unstitched-original-imah9fghmcxxq78g.jpeg?q=70",
    alt: "women saree anand unstitched",
    brand: "Anand Sarees",
    newPrice: 799,
    oldPrice: 1999,
    discount: 60,
    size: "Free",
    idealFor: "W",
    rating: 4.2
  },
  {
    _id: "029",
    name: "Women Saree – BrandK Unstitched (Pink)",
    img: "https://rukminim2.flixcart.com-image/612/612/xif0q/sari/c/w/i/-original-imahfn5hyc329rqv.jpeg?q=70",
    alt: "women saree pink unstitched",
    brand: "BrandK",
    newPrice: 549,
    oldPrice: 1499,
    discount: 63,
    size: "Free",
    idealFor: "W",
    rating: 3.9
  },
  {
    _id: "030",
    name: "Women Saree – Generic Unstitched",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sari/k/g/m/-original-imahgfe5nsjdskxe.jpeg?q=70",
    alt: "women saree generic unstitched",
    brand: "M-Stitch",
    newPrice: 699,
    oldPrice: 1799,
    discount: 61,
    size: "Free",
    idealFor: "W",
    rating: 4.0
  },
  {
    _id: "031",
    name: "Men Graphic T-Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/q/n/a/-original-imahggfekzsbpeyr.jpeg?q=70",
    alt: "men graphic t-shirt",
    brand: "H&M",
    newPrice: 899,
    oldPrice: 1999,
    discount: 55,
    size: "M",
    idealFor: "M",
    rating: 4.1
  },
  {
    _id: "032",
    name: "Men Premium T-Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/i/5/f/s-bul-24bhf120-bullmer-original-imahagca99pxrjg4.jpeg?q=70",
    alt: "men premium t-shirt",
    brand: "Bullmer",
    newPrice: 749,
    oldPrice: 1499,
    discount: 50,
    size: "L",
    idealFor: "M",
    rating: 4.3
  },
  {
    _id: "033",
    name: "Men Casual V-Neck T-Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/a/2/v/l-32015032-glitchez-original-imahgj4zkhpa8fqz.jpeg?q=70",
    alt: "men casual v-neck t-shirt",
    brand: "Glitchez",
    newPrice: 599,
    oldPrice: 1299,
    discount: 54,
    size: "XL",
    idealFor: "M",
    rating: 3.9
  },
  {
    _id: "034",
    name: "Men Roadster Logo T-Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/l/z/l-25060278-roadster-original-imah96pstaasnnkt.jpeg?q=70",
    alt: "men roadster logo t-shirt",
    brand: "Roadster",
    newPrice: 799,
    oldPrice: 1799,
    discount: 55,
    size: "M",
    idealFor: "M",
    rating: 4.0
  },
  {
    _id: "035",
    name: "Men Oversized Graphic T-Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/h/a/0/xxl-gt-4-dyrectdeals-original-imagmg9w2ufvvedf.jpeg?q=70",
    alt: "men oversized graphic t-shirt",
    brand: "DyrectDeals",
    newPrice: 999,
    oldPrice: 2199,
    discount: 54,
    size: "XXL",
    idealFor: "M",
    rating: 4.2
  },
  {
    _id: "036",
    name: "Men Premium Fit T-Shirt",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/d/h/k/m-ts124-vebnor-original-imahgv6mjkvdskth.jpeg?q=70",
    alt: "men premium fit t-shirt",
    brand: "Vebnor",
    newPrice: 699,
    oldPrice: 1499,
    discount: 53,
    size: "L",
    idealFor: "M",
    rating: 3.8
  },
  {
    _id: "037",
    name: "Girls Ethnic Set 12-13 Years – Spamitude",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-ethnic-set/a/o/8/12-13-years-lj-sd-046-spamitude-original-imahfhktssgg7pmd.jpeg?q=70",
    alt: "girls ethnic set 12-13 years spamitude",
    brand: "Spamitude",
    newPrice: 1299,
    oldPrice: 2999,
    discount: 57,
    size: "12-13Years",
    idealFor: "W",
    rating: 4.5
  },
  {
    _id: "038",
    name: "Girls Ethnic Set – Barkat Designing Planet 3-4 Years",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-ethnic-set/z/b/t/3-4-years-set-barkatdesigningplanet-original-imah8mrfhxufe3pp.jpeg?q=70",
    alt: "girls ethnic set 3-4 years barkat designing planet",
    brand: "Barkat Designing Planet",
    newPrice: 1399,
    oldPrice: 3299,
    discount: 57,
    size: "3-4Years",
    idealFor: "W",
    rating: 4.3
  },
  {
    _id: "039",
    name: "Girls Ethnic Set 5-6 Years – Spamitude",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-ethnic-set/w/h/c/5-6-years-lj-sd-046-spamitude-original-imahfhktsyhznycz.jpeg?q=70",
    alt: "girls ethnic set 5-6 years spamitude",
    brand: "Spamitude",
    newPrice: 1199,
    oldPrice: 2699,
    discount: 55,
    size: "5-6Years",
    idealFor: "W",
    rating: 4.2
  },
  {
    _id: "040",
    name: "Girls Ethnic Set – BrandK 8-9 Years",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-ethnic-set/s/z/b/-original-imahfdfzkzx95gfq.jpeg?q=70",
    alt: "girls ethnic set 8-9 years brandk",
    brand: "BrandK",
    newPrice: 1499,
    oldPrice: 3499,
    discount: 57,
    size: "8-9Years",
    idealFor: "W",
    rating: 4.6
  }
];

// Add product to cart
function addToCart(product) {
  let cart = JSON.parse(localStorage.getItem("cart")) || [];
  const exists = cart.find(item => item._id === product._id);
  if (!exists) {
    cart.push(product);
    localStorage.setItem("cart", JSON.stringify(cart));
    alert(`${product.name} added to cart!`);
  } else {
    alert(`${product.name} is already in the cart.`);
  }
}
